import { Card, CardContent } from "@/components/ui/card"
import { ShieldCheck, Zap, Globe, Lock, FileSearch, BarChart3 } from "lucide-react"

const features = [
  {
    icon: ShieldCheck,
    title: "Advanced AI Detection",
    description: "Detect content generated by GPT-4, Claude, Gemini, and other AI models with 98% accuracy.",
  },
  {
    icon: FileSearch,
    title: "Plagiarism Checking",
    description: "Scan billions of web pages and academic papers to find copied content instantly.",
  },
  {
    icon: Zap,
    title: "Instant Results",
    description: "Get comprehensive analysis reports in seconds, not minutes.",
  },
  {
    icon: Globe,
    title: "Multi-Language Support",
    description: "Check content in over 30 languages with the same high accuracy.",
  },
  {
    icon: Lock,
    title: "Privacy First",
    description: "Your content is encrypted and never stored or shared with third parties.",
  },
  {
    icon: BarChart3,
    title: "Detailed Reports",
    description: "Export comprehensive reports with highlighted sections and confidence scores.",
  },
]

export function Features() {
  return (
    <section className="container mx-auto px-4 py-16 md:py-24">
      <div className="text-center mb-12">
        <h2 className="text-3xl md:text-4xl font-bold mb-4 text-balance">Powerful Features for Content Verification</h2>
        <p className="text-muted-foreground text-lg max-w-2xl mx-auto text-balance">
          Everything you need to ensure content authenticity and originality in one platform.
        </p>
      </div>

      <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6 max-w-6xl mx-auto">
        {features.map((feature) => {
          const Icon = feature.icon
          return (
            <Card key={feature.title} className="border-border hover:border-primary/50 transition-colors">
              <CardContent className="pt-6">
                <div className="w-12 h-12 rounded-lg bg-primary/10 flex items-center justify-center mb-4">
                  <Icon className="w-6 h-6 text-primary" />
                </div>
                <h3 className="text-lg font-semibold mb-2">{feature.title}</h3>
                <p className="text-muted-foreground text-sm leading-relaxed">{feature.description}</p>
              </CardContent>
            </Card>
          )
        })}
      </div>
    </section>
  )
}
